# Site settings
title: Code for Ghana
email: info@codeforghana.org
description: > # this means to ignore newlines until "baseurl:"
  Code for Ghana brings developers, journalists, civil-society and government
  together to join hands and use available tools in ICT to make local government 
  better and increase citizen participation
url: http://www.codeforghana.org
# Build settings
markdown: kramdown
